Fix compilation error: remove invalid Property navigation reference
SignEnvelope entity doesn't have a Property navigation property.
Removed env.Property?.Unit reference and set unitNumber to empty string
with TODO to get from ERP via merge service.

This fixes CS1061 compilation error.